export enum GAME_STATUS {
  NOT_STARTED = 'NOT_STARTED',
  STARTED = 'STARTED',
  FINISHED = 'FINISHED',
}

export enum DEAL_STATUS {
  NOT_STARTED = 'NOT_STARTED',
  STARTED = 'STARTED',
  FINISHED = 'FINISHED',
}

export enum PLAYER_STATUS {
  WAITING = 'WAITING',
  READY = 'READY',
}
